### ISSUE TITLE
Unable to establish Trade network - Chapter 4

### ISSUE THREAD

**Issue by rishabv90** [HyperledgerHandsOn/trade-network#10]
[8/8/2021 10:24:06 PM] [ERROR] Error connecting to environment Trade Network: Error: Error querying channels: Could not get all channel names, received: Failed to connect before the deadline on Endorser- name: peer0.carrierorg.trade.com, url:grpcs://localhost:9051, connected:false, connectAttempted:true

I am getting the following error when I follow the steps in the v2 of the book while trying to connect to the Trade Network. Any suggestions on how to fix this ?

**Comment by rcaballeron** [comment]
I'm in the very same situation. I got stuck today at this point.

**Comment by rcaballeron** [comment]
@rishabv90 I was able to solve my issue. In my case the problem was that I used the provide node.json file. Instead of that I've created my own version with the `utils/gen-node-file.js`, repeat the instructions and it finally worked.

The reason is that the `pem` field of the json file changes. This makes sense because you've created your own certificates.

**Comment by VRamakrishna** [comment]
@rishabv90 I'm sorry, I didn't get a notification of your issue in my email, so I'm seeing it for the first time now. Can you try what @rcaballeron suggests? I looked at Chapter 4 again, and we do have instructions asking users to generate the node file using the crypto artifacts they created, rather than using the sample `node.json`, which was meant to serve as a reference.

The only thing to keep in mind, as @rcaballeron points out in a separate issue, is that we refer incorrectly to the `utils` folder as the `scripts` folder. Please generate the node file using the JS file that lies in the `utils` folder.

**Comment by rishabv90** [comment]
Thanks a lot, @VRamakrishna  and @rcaballeron, this surely helps. Great to see this platform with active support.
